# Generated by Django 5.1.1 on 2024-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appInvoice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
