# Generated by Django 5.1.1 on 2024-09-30 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appInvoice', '0002_products_delete_product'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Products',
            new_name='Product',
        ),
    ]
