# Generated by Django 5.1.1 on 2024-09-30 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Connection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_name', models.CharField(max_length=10)),
                ('c_company_name', models.CharField(max_length=15)),
                ('c_mobile_no', models.IntegerField()),
                ('c_email', models.EmailField(max_length=254, null=True)),
                ('c_website', models.URLField(null=True)),
                ('c_industry', models.CharField(max_length=10, null=True)),
                ('c_segment', models.CharField(max_length=10, null=True)),
                ('c_city', models.CharField(max_length=10)),
                ('c_state', models.CharField(max_length=10)),
                ('c_country', models.CharField(max_length=10)),
                ('c_billing_address', models.TextField()),
                ('c_shipping_address', models.TextField()),
                ('c_connection_type', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Connection_Bank_Details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cbd_bank_name', models.CharField(max_length=10)),
                ('cbd_branch', models.CharField(max_length=10)),
                ('cbd_account_no', models.IntegerField()),
                ('cbd_ifsc', models.CharField(max_length=10)),
                ('cbd_swift_code', models.CharField(max_length=10)),
            ],
        ),
    ]
