# Generated by Django 5.1.1 on 2024-10-12 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0002_alter_invoiceitem_amount_alter_invoiceitem_igst'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
    ]
