# Generated by Django 5.1.1 on 2024-10-16 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0003_alter_invoice_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='cgst',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='igst',
            field=models.DecimalField(blank=True, decimal_places=2, default=3.0, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='sgst',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='taxable',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=10),
        ),
    ]
