# Generated by Django 5.1.1 on 2024-10-27 14:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connections', '0002_delete_connection_bank_details_connection_c_gstin_and_more'),
        ('invoice', '0010_alter_invoice_connection_alter_invoice_invoice_date_and_more'),
        ('products', '0004_remove_product_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='connection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='connections.connection'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
        migrations.AlterField(
            model_name='invoiceitem',
            name='rate',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
