# Generated by Django 5.1.1 on 2024-11-03 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice', '0012_invoiceitem_a_cgst'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='a_cgst',
        ),
        migrations.AddField(
            model_name='invoice',
            name='a_cgst',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True),
        ),
    ]
