# Generated by Django 5.1.1 on 2024-10-07 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_hsn',
            field=models.IntegerField(default=32543),
        ),
        migrations.AddField(
            model_name='product',
            name='product_unit',
            field=models.CharField(default='No.s.', max_length=5),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
