# Generated by Django 5.1.1 on 2024-10-09 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_product_hsn_product_product_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='product_unit',
        ),
    ]
